---
title: "Lab 00 - Hello IDS!"
author: "James Chalmers"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("James", "A", "B", 
           "C", "D"),
  github_username = c("JamesChalmers110","One", "Two", 
                      "Three", "Four"), 
  colour = c("Red", "Yellow", "Green", 
             "Black", "Blue"),
  hobby = c("Climbing", "Sitting", "Standing", 
            "Stalling", "Sleeping"),
  favourite_number = c(2, 7, 3, 9, 1)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

The code creates a bar chart with each username on the x-axis and their number on the y-axis; each bar is shaded with the team member's favourite colour.

